import { ElementModal, LoginModal, Modal, MountedClient, Navbar, RegisterModal } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/providers/ReduxProvider";
import ToastProvider from "@/providers/ToastProvider";
import getCurrentUser from "./actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  console.log(user, "user")
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <MountedClient>
            <ToastProvider/>
            <ElementModal />
            <LoginModal />
            <RegisterModal />
            <Navbar user={user}/>
          </MountedClient>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
